spring.datasource.url=jdbc:mysql://localhost:3306/vitalife
spring.datasource.username=root
spring.datasource.password=ghostofc99

cashflow.openapi.dev-url=http://localhost:8080
cashflow.openapi.prod-url=https://cashflow-api.com

